- name: Copy config file
  copy:
    src: glance-api.conf
    dest: /etc/glance/glance-api.conf
    owner: root
    group: glance
    mode: 0640
  when: ansible_distribution == "CentOS"

- name: Populate the database
  command: su -s /bin/sh -c "glance-manage db_sync" glance
  failed_when: false
  no_log: true
  when: ansible_distribution == "CentOS"

- name: Restart glance-api
  service:
    name: openstack-glance-api.service
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

